import type { Trip, DayPlan, ChatMessage } from "./types";

export const MOCK_TRIP: Trip = {
  id: "trip-1",
  title: "Summer in Tokyo 2024",
  startDate: "2024-08-12",
  endDate: "2024-08-19",
};

export const MOCK_DAYS: DayPlan[] = [
  {
    dayIndex: 0,
    date: "2024-08-12",
    label: "Day 1",
    subtitle: "Mon, Aug 12 — Arrival & Shibuya",
    activities: [
      {
        id: "a1",
        dayIndex: 0,
        orderIndex: 0,
        time: "10:30 AM",
        title: "Arrive at Narita Airport",
        description: "Terminal 1 — Pick up JR Pass & Pocket WiFi",
        category: "transport",
        mapPosition: { x: 82, y: 28 },
      },
      {
        id: "a2",
        dayIndex: 0,
        orderIndex: 1,
        time: "1:00 PM",
        title: "Check in — Shibuya Stream Hotel",
        description: "Superior Double Room, 14F — Early check-in confirmed",
        category: "hotel",
        mapPosition: { x: 38, y: 45 },
      },
      {
        id: "a3",
        dayIndex: 0,
        orderIndex: 2,
        time: "2:30 PM",
        title: "Coffee at About Life Coffee",
        description: "Specialty pour-over in Dogenzaka — Try the Kenya single origin",
        category: "food",
        mapPosition: { x: 32, y: 52 },
      },
      {
        id: "a4",
        dayIndex: 0,
        orderIndex: 3,
        time: "4:00 PM",
        title: "Shibuya Sky Observation Deck",
        description: "46F open-air rooftop — Best views at golden hour",
        category: "attraction",
        mapPosition: { x: 42, y: 40 },
      },
      {
        id: "a5",
        dayIndex: 0,
        orderIndex: 4,
        time: "7:00 PM",
        title: "Ce La Vi Tokyo",
        description: "Rooftop dining at Tokyu Plaza — Asian fusion, great sunset views",
        category: "food",
        mapPosition: { x: 36, y: 48 },
        status: "just_added",
      },
    ],
  },
  {
    dayIndex: 1,
    date: "2024-08-13",
    label: "Day 2",
    subtitle: "Tue, Aug 13 — Senso-ji & Asakusa",
    activities: [
      {
        id: "a6",
        dayIndex: 1,
        orderIndex: 0,
        time: "7:00 AM",
        title: "Sunrise at Tsukiji Outer Market",
        description: "Fresh sushi breakfast at Tsukiji — arrive early for best selection",
        category: "food",
        mapPosition: { x: 45, y: 35 },
      },
      {
        id: "a7",
        dayIndex: 1,
        orderIndex: 1,
        time: "9:00 AM",
        title: "Senso-ji Temple",
        description: "Tokyo's oldest temple — explore the grounds and souvenir shops",
        category: "attraction",
        mapPosition: { x: 50, y: 32 },
      },
      {
        id: "a8",
        dayIndex: 1,
        orderIndex: 2,
        time: "11:30 AM",
        title: "Nakamise Shopping Street",
        description: "Traditional souvenirs and snacks — negotiate prices",
        category: "shopping",
        mapPosition: { x: 48, y: 33 },
      },
      {
        id: "a9",
        dayIndex: 1,
        orderIndex: 3,
        time: "1:30 PM",
        title: "Ramen at Ichiran",
        description: "Tonkotsu ramen — try the spicy option",
        category: "food",
        mapPosition: { x: 49, y: 34 },
      },
      {
        id: "a10",
        dayIndex: 1,
        orderIndex: 4,
        time: "3:00 PM",
        title: "Asakusa Culture & Tourist Information Center",
        description: "8F observation deck with free views of Senso-ji",
        category: "attraction",
        mapPosition: { x: 51, y: 31 },
      },
      {
        id: "a11",
        dayIndex: 1,
        orderIndex: 5,
        time: "6:00 PM",
        title: "Ryokan Dinner Experience",
        description: "Traditional kaiseki at Asakusa Ryokan — 7-course meal",
        category: "food",
        mapPosition: { x: 52, y: 30 },
      },
    ],
  },
  {
    dayIndex: 2,
    date: "2024-08-14",
    label: "Day 3",
    subtitle: "Wed, Aug 14 — Meiji & Harajuku",
    activities: [
      {
        id: "a12",
        dayIndex: 2,
        orderIndex: 0,
        time: "8:30 AM",
        title: "Meiji Shrine Walk",
        description: "Peaceful forest shrine — 15 min walk through woods",
        category: "attraction",
        mapPosition: { x: 28, y: 25 },
      },
      {
        id: "a13",
        dayIndex: 2,
        orderIndex: 1,
        time: "10:00 AM",
        title: "Crepes at Takeshita Street",
        description: "Famous pedestrian shopping street — try matcha or strawberry crepe",
        category: "food",
        mapPosition: { x: 32, y: 28 },
      },
      {
        id: "a14",
        dayIndex: 2,
        orderIndex: 2,
        time: "12:00 PM",
        title: "Omotesando Shopping",
        description: "Tokyo's Champs-Élysées — luxury boutiques and cafes",
        category: "shopping",
        mapPosition: { x: 30, y: 26 },
      },
      {
        id: "a15",
        dayIndex: 2,
        orderIndex: 3,
        time: "2:30 PM",
        title: "Yoyogi Park",
        description: "Central park with pond and walking trails",
        category: "attraction",
        mapPosition: { x: 29, y: 24 },
      },
      {
        id: "a16",
        dayIndex: 2,
        orderIndex: 4,
        time: "5:00 PM",
        title: "Character Street (Ghibli Museum Gift Shop)",
        description: "Exclusive Studio Ghibli merchandise",
        category: "shopping",
        mapPosition: { x: 31, y: 27 },
      },
      {
        id: "a17",
        dayIndex: 2,
        orderIndex: 5,
        time: "7:30 PM",
        title: "Tonki Tonkatsu",
        description: "Legendary tonkatsu restaurant — best breaded pork cutlet in Tokyo",
        category: "food",
        mapPosition: { x: 33, y: 29 },
      },
    ],
  },
  {
    dayIndex: 3,
    date: "2024-08-15",
    label: "Day 4",
    subtitle: "Thu, Aug 15 — Ginza & Tsukiji",
    activities: [
      {
        id: "a18",
        dayIndex: 3,
        orderIndex: 0,
        time: "9:00 AM",
        title: "Ginza Walking Tour",
        description: "High-end shopping district — window shop at flagship stores",
        category: "shopping",
        mapPosition: { x: 55, y: 45 },
      },
      {
        id: "a19",
        dayIndex: 3,
        orderIndex: 1,
        time: "11:00 AM",
        title: "Kabuki-za Theater Tour",
        description: "Traditional kabuki theater — see matinee performance or tour",
        category: "attraction",
        mapPosition: { x: 56, y: 46 },
      },
      {
        id: "a20",
        dayIndex: 3,
        orderIndex: 2,
        time: "1:00 PM",
        title: "Sushi at Daiwa Sushi",
        description: "Michelin-starred omakase at Tsukiji — book ahead",
        category: "food",
        mapPosition: { x: 46, y: 36 },
      },
      {
        id: "a21",
        dayIndex: 3,
        orderIndex: 3,
        time: "3:00 PM",
        title: "Tokyo Station Area",
        description: "Historic station building and shopping complex",
        category: "shopping",
        mapPosition: { x: 60, y: 50 },
      },
      {
        id: "a22",
        dayIndex: 3,
        orderIndex: 4,
        time: "5:30 PM",
        title: "Sumida River Cruise",
        description: "45-minute boat ride with views of Tokyo bridges",
        category: "transport",
        mapPosition: { x: 52, y: 40 },
      },
      {
        id: "a23",
        dayIndex: 3,
        orderIndex: 5,
        time: "7:30 PM",
        title: "Izakaya Dinner",
        description: "Traditional Japanese tavern — yakitori and sake",
        category: "food",
        mapPosition: { x: 58, y: 48 },
      },
    ],
  },
  {
    dayIndex: 4,
    date: "2024-08-16",
    label: "Day 5",
    subtitle: "Fri, Aug 16 — Akihabara & Ueno",
    activities: [
      {
        id: "a24",
        dayIndex: 4,
        orderIndex: 0,
        time: "10:00 AM",
        title: "Akihabara Electronic District",
        description: "Tech paradise — visit Yodobashi, Don Quijote, and game arcades",
        category: "shopping",
        mapPosition: { x: 62, y: 42 },
      },
      {
        id: "a25",
        dayIndex: 4,
        orderIndex: 1,
        time: "12:30 PM",
        title: "Maid Cafe Experience",
        description: "Themed cafe in Akihabara — sit, drink, and be entertained",
        category: "food",
        mapPosition: { x: 63, y: 41 },
      },
      {
        id: "a26",
        dayIndex: 4,
        orderIndex: 2,
        time: "2:00 PM",
        title: "Tokyo National Museum",
        description: "Japan's largest museum — samurai armor, Buddhist art, pottery",
        category: "attraction",
        mapPosition: { x: 65, y: 38 },
      },
      {
        id: "a27",
        dayIndex: 4,
        orderIndex: 3,
        time: "4:00 PM",
        title: "Ueno Park",
        description: "Large urban park with ponds and temples",
        category: "attraction",
        mapPosition: { x: 64, y: 37 },
      },
      {
        id: "a28",
        dayIndex: 4,
        orderIndex: 4,
        time: "6:00 PM",
        title: "Ameya Yokocho Market",
        description: "Historic shopping street — street food and bargains",
        category: "shopping",
        mapPosition: { x: 63, y: 39 },
      },
      {
        id: "a29",
        dayIndex: 4,
        orderIndex: 5,
        time: "8:00 PM",
        title: "Okonomiyaki at Kiji",
        description: "Savory pancakes — watch chef prepare at teppan griddle",
        category: "food",
        mapPosition: { x: 61, y: 40 },
      },
    ],
  },
  {
    dayIndex: 5,
    date: "2024-08-17",
    label: "Day 6",
    subtitle: "Sat, Aug 17 — Shinjuku & Nightlife",
    activities: [
      {
        id: "a30",
        dayIndex: 5,
        orderIndex: 0,
        time: "11:00 AM",
        title: "Tokyo Metropolitan Government Building",
        description: "Free observation deck on 45th floor — 360° city views",
        category: "attraction",
        mapPosition: { x: 35, y: 40 },
      },
      {
        id: "a31",
        dayIndex: 5,
        orderIndex: 1,
        time: "1:00 PM",
        title: "Lunch at Gonpachi",
        description: "Modern izakaya with seasonal dishes — great for groups",
        category: "food",
        mapPosition: { x: 36, y: 41 },
      },
      {
        id: "a32",
        dayIndex: 5,
        orderIndex: 2,
        time: "2:30 PM",
        title: "Shinjuku Shopping & Arcades",
        description: "Game centers and department stores — 3D entertainment",
        category: "shopping",
        mapPosition: { x: 37, y: 42 },
      },
      {
        id: "a33",
        dayIndex: 5,
        orderIndex: 3,
        time: "5:00 PM",
        title: "Memory Lane (Omoide Yokocho)",
        description: "Narrow alley with retro bars and restaurants from 1950s",
        category: "attraction",
        mapPosition: { x: 34, y: 39 },
      },
      {
        id: "a34",
        dayIndex: 5,
        orderIndex: 4,
        time: "6:30 PM",
        title: "Karaoke at Shidax",
        description: "Popular chain — book private room for group session",
        category: "attraction",
        mapPosition: { x: 36, y: 43 },
      },
      {
        id: "a35",
        dayIndex: 5,
        orderIndex: 5,
        time: "9:00 PM",
        title: "Yakitori Alley Dinner",
        description: "Grilled chicken skewers and beer — authentic local experience",
        category: "food",
        mapPosition: { x: 38, y: 44 },
      },
    ],
  },
  {
    dayIndex: 6,
    date: "2024-08-18",
    label: "Day 7",
    subtitle: "Sun, Aug 18 — Odaiba & Departure",
    activities: [
      {
        id: "a36",
        dayIndex: 6,
        orderIndex: 0,
        time: "9:00 AM",
        title: "Tsukiji Outer Market Breakfast",
        description: "Final sushi breakfast — last chance for fresh seafood",
        category: "food",
        mapPosition: { x: 45, y: 35 },
      },
      {
        id: "a37",
        dayIndex: 6,
        orderIndex: 1,
        time: "10:30 AM",
        title: "Odaiba Ferris Wheel (Palette Town)",
        description: "135m observation wheel — views of Rainbow Bridge and Bay",
        category: "attraction",
        mapPosition: { x: 25, y: 55 },
      },
      {
        id: "a38",
        dayIndex: 6,
        orderIndex: 2,
        time: "12:30 PM",
        title: "Decks Shopping Mall",
        description: "Entertainment complex with food court and shops",
        category: "shopping",
        mapPosition: { x: 26, y: 56 },
      },
      {
        id: "a39",
        dayIndex: 6,
        orderIndex: 3,
        time: "2:00 PM",
        title: "teamLab Borderless (Optional)",
        description: "Digital art museum — immersive experience (may need early booking)",
        category: "attraction",
        mapPosition: { x: 24, y: 54 },
      },
      {
        id: "a40",
        dayIndex: 6,
        orderIndex: 4,
        time: "4:00 PM",
        title: "Souvenir Shopping at Airport",
        description: "Last-minute gifts at Narita terminal shops",
        category: "shopping",
        mapPosition: { x: 80, y: 20 },
      },
      {
        id: "a41",
        dayIndex: 6,
        orderIndex: 5,
        time: "5:30 PM",
        title: "Depart from Narita Airport",
        description: "Check-in 2 hours early — 3-hour airport procedure",
        category: "transport",
        mapPosition: { x: 82, y: 28 },
      },
    ],
  },
];

export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    role: "user",
    content: "Can you suggest a nice dinner spot near Shibuya for tonight? Something with a view would be great.",
    timestamp: "3:42 PM",
  },
  {
    id: "m2",
    role: "assistant",
    content: "Great choice! Here's a top pick for dinner with a view in Shibuya:",
    timestamp: "3:42 PM",
    suggestion: {
      title: "Ce La Vi Tokyo",
      description: "Rooftop dining at Tokyu Plaza Shibuya. Asian fusion cuisine with panoramic city views. Perfect for sunset dinner.",
      rating: 4.6,
      imageUrl: "",
      addedToTrip: true,
    },
  },
];

export const MOCK_QUICK_ACTIONS = [
  "Optimize Route",
  "Find similar",
  "Cheaper alternatives",
];

export const CANNED_RESPONSE: ChatMessage = {
  id: "",
  role: "assistant",
  content: "I found a couple of great options! Let me know if you'd like more details or want to add any of these to your itinerary.",
  timestamp: "",
};
